# Automatically label PRs based on changed files

'dependencies':
  - changed-files:
    - any-glob-to-any-file: ['package.json', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml']

'docker':
  - changed-files:
    - any-glob-to-any-file: ['Dockerfile', 'docker-compose.yml', '.dockerignore']

'ci/cd':
  - changed-files:
    - any-glob-to-any-file: ['.github/workflows/**']

'documentation':
  - changed-files:
    - any-glob-to-any-file: ['**/*.md', 'docs/**']

'components':
  - changed-files:
    - any-glob-to-any-file: ['src/components/**']

'styles':
  - changed-files:
    - any-glob-to-any-file: ['**/*.css', '**/*.scss', 'src/theme/**']

'tests':
  - changed-files:
    - any-glob-to-any-file: ['**/*.test.ts', '**/*.test.tsx', '**/*.spec.ts', '**/*.spec.tsx', 'jest.config.js']

'api':
  - changed-files:
    - any-glob-to-any-file: ['src/app/api/**']

'config':
  - changed-files:
    - any-glob-to-any-file: ['*.config.js', '*.config.ts', 'tsconfig.json', '.eslintrc*']
